---
- name: Launch periodics
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    levant_file: ../../../levant.yml
    jobs_dir: ../../../jobs/periodic

  tasks:
    - name: Launch periodic jobs
      command: levant deploy -var-file={{ levant_file }} {{ jobs_dir}}/{{ item }}.nomad
      loop:
      - prune-downloads
      - update-services
      ignore_errors: true
