- name: Install Docker
  hosts: all
  become: yes

  vars:
    docker_users:
      - brent
      - plex
    docker_daemon_options: {'dns': ["192.168.10.2"]}

    pip_install_packages:
      - name: docker

  roles:
    - docker
    - pip

  tasks:
    - name: Copy clean_docker script to remote server
      ansible.builtin.copy:
        src: ../../../scripts/clean_docker.sh
        dest: /etc/cron.daily/clean_docker
        mode: '0755'
