---
global:
  scrape_interval:     5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'traefik_metrics'
    static_configs:
    - targets: ['traefik.service.consul:8082']

  - job_name: 'nomad_metrics'
    consul_sd_configs:
    - server: 'consul.service.consul:8500'
      services: ['nomad-client', 'nomad']
    relabel_configs:
    - source_labels: ['__meta_consul_tags']
      regex: '(.*)http(.*)'
      action: keep
    scrape_interval: 5s
    metrics_path: /v1/metrics
    params:
      format: ['prometheus']

  - job_name: 'consul_metrics'
    metrics_path: /metrics
    consul_sd_configs:
      - server: 'consul.service.consul:8500'
    relabel_configs:
    - source_labels: [__meta_consul_service]
      regex: (.+)-sidecar-proxy
      action: drop
    - source_labels: [__meta_consul_service]
      regex: (.+)
      target_label: service
    - source_labels: [__meta_consul_service_metadata_metrics_port_envoy]
      regex: (.+)
      action: keep
    - source_labels: [__address__,__meta_consul_service_metadata_metrics_port_envoy]
      regex: (.+)(?::\d+);(\d+)
      action: replace
      replacement: $1:$2
      target_label: __address__
    scrape_interval: 5s
