- name: Install dnsmasq
  hosts: network_hosts
  become: yes

  vars:
    - dnsmasq_port: 53
    - dnsmasq_enable_tftp: no
    - dnsmasq_conf_dir: /etc/dnsmasq.d
    - dnsmasq_bogus_priv: no
    - dnsmasq_dnssec: no
    - dnsmasq_no_resolv: yes
    - dnsmasq_servers:
      - nameserver: 192.168.10.1

  roles:
    - robertdebock.dnsmasq

  tasks:
  - name: Copy dnsmasq configuration
    copy:
      src: "{{ item }}"
      dest: /etc/dnsmasq.d/
      owner: root
      group: root
      mode: '0644'
    with_fileglob:
      - ../../config/dnsmasq/*

  - name: Start dnsmasq.service
    systemd:
      name: dnsmasq.service
      state: started
      enabled: yes
