- name: Prep all systems for install
  hosts: all
  become: yes
  tasks:
    - name: Create sudo rules for user 'brent'
      copy:
        dest: "/etc/sudoers.d/nopasswd"
        content: |
          brent  ALL=(ALL) NOPASSWD:ALL

    - name: Set fastestmirror in dnf configuration
      lineinfile:
        path: /etc/dnf/dnf.conf
        regexp: '^fastestmirror='
        line: 'fastestmirror=1'
      when: ansible_distribution == 'CentOS' and ansible_distribution_major_version|int >= 8

    - name: Update all packages
      yum:
        name: '*'
        state: latest

    - name: Disable firewalld
      ansible.builtin.systemd:
        name: firewalld
        state: stopped
        enabled: false

    - name: Disable SELinux
      ansible.posix.selinux:
        policy: targeted
        state: disabled
      register: selinux_status

    - name: Check if a reboot is required
      set_fact:
        reboot_required: "{{ selinux_status.reboot_required }}"

    - name: Reboot the system if necessary
      reboot:
      when: reboot_required

