- name: Install Docker
  hosts: all
  become: yes

  vars:
    docker_users:
      - brent
      - plex
    docker_daemon_options: {'dns': ["172.17.0.1"]}

  roles:
    - geerlingguy.docker

  tasks:
    - name: Add docker cleanup to cron
      ansible.builtin.copy:
        dest: "/etc/cron.d/clean-docker"
        content: |
          35 6 * * * root /usr/bin/docker image prune -f >/dev/null 2>&1
