- name: Install Docker
  hosts: all
  become: yes

  roles:
    - geerlingguy.docker

  tasks:
    - name: Add docker cleanup to cron
      ansible.builtin.copy:
        dest: "/etc/cron.d/clean-docker"
        content: |
          35 6 * * * root /usr/bin/docker image prune -f >/dev/null 2>&1
