- name: Prep local system for install
  hosts: localhost
  connection: local
  become: yes

  tasks:
    - name: Install HashiCorp tap
      community.general.homebrew_tap:
        name: hashicorp/tap
        url: https://github.com/hashicorp/homebrew-tap
        state: present
      when: ansible_distribution == 'MacOSX'

    - name: Update homebrew
      community.general.homebrew:
        update_homebrew: true
      when: ansible_distribution == 'MacOSX'

    # Install formula foo with 'brew' in default path
    - name: Install packages via homebrew
      community.general.homebrew:
        name:
          - levant
          - nomad
          - consul
          - restic
        state: present
      when: ansible_distribution == 'MacOSX'

    - name: Install python dependencies
      command: /usr/bin/env pip3 install "{{ item }}"
      loop:
      - python-consul
      - pyyaml
