---
- name: Initialize secrets from vars/secrets.yml
  hosts: localhost
  connection: local

  vars:
    consul_address: "{{ groups['consul_instances'][0] }}"
    rclone_conf: "{{ lookup('file', rclone_conf_filename) }}"

  tasks:
    - name: include secrets file
      include_vars: 'vars/secrets.yml'

    - name: Write out authelia_jwt_secret to Consul
      consul_kv:
        key: authelia/config/jwt_secret
        value: "{{ authelia_jwt_secret | default(lookup('ansible.builtin.password', '/dev/null length=64 chars=ascii_letters'), true) }}"
        host: "{{ consul_address }}"
        
    - name: Write out authelia_session_secret to Consul
      consul_kv:
        key: authelia/config/session_secret
        value: "{{ authelia_session_secret | default(lookup('ansible.builtin.password', '/dev/null length=64 chars=ascii_letters'), true) }}"
        host: "{{ consul_address }}"
        
    - name: Write out authelia_encryption_key to Consul
      consul_kv:
        key: authelia/config/encryption_key
        value: "{{ authelia_encryption_key | default(lookup('ansible.builtin.password', '/dev/null length=64 chars=ascii_letters'), true) }}"
        host: "{{ consul_address }}"
        
    - name: Write out authelia_smtp_password to Consul
      consul_kv:
        key: authelia/config/smtp_password
        value: "{{ authelia_smtp_password }}"
        host: "{{ consul_address }}"

    - name: Write out flame password to Consul
      consul_kv:
        key: flame/config/password
        value: "{{ flame_password }}"
        host: "{{ consul_address }}"

    - name: Write out Cloudflare e-mail address
      consul_kv:
        key: traefik/config/cloudflare_email
        value: "{{ cloudflare_email }}"
        host: "{{ consul_address }}"

    - name: Write out Cloudflare DNS API token
      consul_kv:
        key: traefik/config/dns_api_token
        value: "{{ cloudflare_dns_api_token }}"
        host: "{{ consul_address }}"

    - name: Write out Restic password config
      consul_kv:
        key: restic/config/restic_password
        value: "{{ restic_password | default(lookup('ansible.builtin.password', '/dev/null length=32 chars=ascii_letters'), true) }}"
        host: "{{ consul_address }}"

    - name: Write out Plex claim token
      consul_kv:
        key: plex/config/claim_token
        value: "{{ plex_claim_token }}"
        host: "{{ consul_address }}"

    - name: Write out rclone.conf configuration for Restic
      consul_kv:
        key: rclone/config/rclone.conf
        value: "{{ rclone_conf }}"
        host: "{{ consul_address }}"

    - name: Write out type configuration for rclone
      consul_kv:
        key: rclone/config/type
        value: "{{ lookup('ansible.builtin.ini', 'type', section='google-drive', file=rclone_conf_filename) }}"
        host: "{{ consul_address }}"

    - name: Write out type configuration for rclone
      consul_kv:
        key: rclone/config/type
        value: "{{ lookup('ansible.builtin.ini', 'type', section='google-drive', file=rclone_conf_filename) }}"
        host: "{{ consul_address }}"

    - name: Write out client_id configuration for rclone
      consul_kv:
        key: rclone/config/client_id
        value: "{{ lookup('ansible.builtin.ini', 'client_id', section='google-drive', file=rclone_conf_filename) }}"
        host: "{{ consul_address }}"

    - name: Write out client_secret configuration for rclone
      consul_kv:
        key: rclone/config/client_secret
        value: "{{ lookup('ansible.builtin.ini', 'client_secret', section='google-drive', file=rclone_conf_filename) }}"
        host: "{{ consul_address }}"

    - name: Write out token configuration for rclone
      consul_kv:
        key: rclone/config/token
        value: "{{ lookup('ansible.builtin.ini', 'token', section='google-drive', file=rclone_conf_filename) }}"
        host: "{{ consul_address }}"

    - name: Write out root_folder_id configuration for rclone
      consul_kv:
        key: rclone/config/root_folder_id
        value: "{{ lookup('ansible.builtin.ini', 'root_folder_id', section='google-drive', file=rclone_conf_filename) }}"
        host: "{{ consul_address }}"
