---
- name: Initialize service configuration in Consul
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    levant_filename: "../../../levant.yml"
    init_services_filename: "../../../scripts/init_services.py"

  tasks:
    - name: Execute init_services.py on local
      command: /usr/bin/env python3 {{ init_services_filename }} -f {{ levant_filename }} -c {{ groups['consul_instances'][0] }}
